
image: ruby:2.5
variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"

stages:
  - build
  - deploy

build:
  tags:
    - docs
  stage: build
  artifacts:
    paths:
      - _site/
  script:
    - |
      cat /etc/debian_version || true
      uname -a
      echo "Merge marker sanity check"
      (grep -ri "<<<<<<" * || grep -ri ">>>>>>" *) && (echo "found some merge conflicts, will abort"; exit -1)

      echo "## removing old _site directory"
      rm -rf ./_site

      echo "## building docs"
      bundle install
      bundle exec jekyll build --config _config.yml,_versions.yml

deploy:
  tags:
    - docs
  stage: deploy
  image: ubuntu:22.04
  variables:
    upload_dir: docs    
  dependencies:
    - build
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq lftp openssh-client
    - echo "Building branch $CI_COMMIT_REF_NAME"
    - echo "Set SSH configuration for SFTP"
    - eval $(ssh-agent -s)
    - echo "$sftp_user_private_key_base64" | base64 -d | tr -d '\r' | ssh-add -

  script:
    - |
      # if [[ ! $CI_COMMIT_BRANCH =~ ^7.x-[0-9]{2}$  ]]; then
      #   echo "Branch $CI_COMMIT_BRANCH does not seem to be a release branch, exiting gracefully"
      #   exit 0
      # fi
      
      
      #8pc TODO replace 
      sftp_user_name=docs

      #set default SFTP server
      if [ ! ${sftp_server+x} ];  then
        sftp_server=18.203.166.154
      fi
      
      echo "Building branch $git_branch"

      docs_version=$(cat _versions.yml | grep "^baseurl:" | cut -d ':' -f2 | tr -d " '" | sed 's/\/docs\///')
      echo "Uploading files to SFTP server $sftp_server with user $sftp_user_name and upload_dir: $upload_dir and version $docs_version"
      lftp --version
      echo "Start SFTP upload"


      lftp -u $sftp_user_name, -e "set sftp:connect-program 'ssh -a -x -o StrictHostKeyChecking=no';mkdir -p /var/www/$upload_dir/html/$docs_version;  mirror --reverse --delete --parallel=20 --verbose _site/ /var/www/$upload_dir/html/$docs_version/; quit" sftp://$sftp_server




