markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: "1..2"
  parse_block_html: false
  syntax_highlighter_opts:
    disable: true

sass:
  style: compressed
  sass_dir: ./sass

exclude: ['*.sh', 'build_releasenotes.rb', 'sass', '.idea', '.jekyll-cache', 'README*']

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll

elasticsearch:
  currentversion: 7.6.0
  previousversion: 7.5.2

searchguard:
  esmajorversion: 7
  version: 7.x-40.0.0 
  fullversion: 7.5.1-40.0.0 
  nextminorversion: 7.5.1-40.1.0 
  nextmajorversion: 7.5.1-41.0.0 
  islatestversion: true
  ispreliminaryversion: false
  allversions:
    - flx
    - 7x-53
    - 7x-52  
    - 7x-51  
    - 7x-50  
    - 7x-49  
    - 7x-48  
    - 7x-47
    - 7x-46
    - 7x-45
    - 7x-43
    - 7x-42
    - 7x-41
    - 7x-40
    - 7x-38
    - 7x-37
    - 7x-36
    - 7x-35
    - 6x-25
    - 6x-24
    - 6x-23
    - 6x-22
    - 6x-21
    - 6x-20
    - v5
    - v2

docroots: 
  flx: latest
  7x-53: 7.x-53
  7x-52: 7.x-52
  7x-51: 7.x-51
  7x-50: 7.x-50
  7x-49: 7.x-49
  7x-48: 7.x-48
  7x-47: 7.x-47  
  7x-46: 7.x-46
  7x-45: 7.x-45
  7x-43: 7.x-43
  7x-42: 7.x-42
  7x-41: 7.x-41
  7x-40: 7.x-40
  7x-38: 7.x-38
  7x-37: 7.x-37
  7x-36: 7.x-36
  7x-35: 7.x-35
  6x-25: 6.x-25
  6x-24: 6.x-24
  6x-23: 6.x-23
  6x-22: 6.x-22
  6x-21: 6.x-21
  6x-20: 6.x-20
  v5: v5
  v2: v2

index: false

labels:
  navigation:
    introduction: Introduction to Search Guard
    quickstart: Quickstart
    password-based: Password-based authentication
    first_steps: First steps
    versions: Search Guard Versions
    installation: Installing Search Guard
    upgrading: Upgrading Search Guard
    tls: TLS Setup
    ldap: Active Directory / LDAP
    generating-certificates: "Generating certificates"
    configuration: "Search Guard Configuration"
    sgctl: "Search Guard CTL"
    authauth: Authentication
    rolespermissions: "Authorization"
    eeadvanced: Advanced Security Features
    jwt: "JSON web tokens"
    proxy: "Proxy Authentication"
    sg_authc: "Authentication"
    authorization-advanced: "Advanced Authentication"
    dlsfls: Document- and Field-Level Security
    dls: "Document-Lecel Security"
    kibana: Kibana
    auditlog: Audit And Compliance Logging
    compliance: Compliance
    restapi: REST API
    elasticstack: Integrating with the Elasticstack
    elasticstack-alternatives: "Elasticstack alternatives"
    kibana-authentication: "Kibana Authentication"
    kibana-authentication-migration-overview: "Migration from v52"
    kibana-advanced: "Kibana Advanced Settings"
    kibana-authentication-basic-overview: "Password based authentication"
    kibana-authentication-openid-overview: "OpenID authentication"
    kibana-authentication-saml-overview: "SAML authentication"
    otherintegrations: Other integrations
    systemintegrators: Advanced system integrator features
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    changelogs-kibana: "Kibana Changelogs"
    changelogs-searchguard: "Search Guard Changelogs"
    changelogs-tlstool: "TLS Tool Changelogs"
    resources: Resources
    signals: Signals Alerting
    actions: Alerting Actions
    conditions: Conditions
    inputs: Alerting inputs
    signals-rest: REST API
    security: Alerting Security
    transformations: Transformations
    triggers: Triggers
    advanced-topics: Signals Advanced Topics
    sgadmin: sgadmin
    flx: Search Guard FLX
    7x-53: Search Guard 7.x-53     
    7x-52: Search Guard 7.x-52     
    7x-51: Search Guard 7.x-51    
    7x-50: Search Guard 7.x-50    
    7x-49: Search Guard 7.x-49    
    7x-48: Search Guard 7.x-48    
    7x-47: Search Guard 7.x-47
    7x-46: Search Guard 7.x-46    
    7x-45: Search Guard 7.x-45    
    7x-43: Search Guard 7.x-43
    7x-42: Search Guard 7.x-42
    7x-41: Search Guard 7.x-41
    7x-40: Search Guard 7.x-40
    7x-38: Search Guard 7.x-38
    7x-37: Search Guard 7.x-37
    7x-36: Search Guard 7.x-36
    7x-35: Search Guard 7.x-35
    6x-25: Search Guard 6.x-25
    6x-24: Search Guard 6.x-24
    6x-23: Search Guard 6.x-23
    6x-22: Search Guard 6.x-22
    6x-21: Search Guard 6.x-21
    6x-20: Search Guard 6.x-20
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs_introduction: Introduction to Search Guard
    docs_quickstart: Documentation
    docs_first_steps: First steps
    docs_versions: Documentation
    docs_installation: Documentation
    docs_tls: Documentation
    docs_configuration_changes: Documentation
    docs_auth_auth: Documentation
    docs_roles_permissions: Documentation
    docs_dls_fls: Documentation
    docs_audit_logging: Documentation
    docs_rest_api: Documentation
    docs_kibana: Documentation
    docs_elasticstack: Documentation
    docs_other_integrations: Documentation
    docs_systemintegrators: Documentation
    docs_signals: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    resources: Resources

relative_links:
  enabled:     true
  collections: true

#domain: https://docs.search-guard.com
#baseurl: /tech-preview

collections_dir: _content

collections:
  docs_introduction:
    output: true
    permalink: :name
  docs_quickstart:
    output: true
    permalink: :name
  docs_versions:
    output: true
    permalink: :name
  docs_installation:
    output: true
    permalink: :name
  docs_tls:
    output: true
    permalink: :name
  docs_configuration_changes:
    output: true
    permalink: :name
  docs_auth_auth:
    output: true
    permalink: :name
  docs_roles_permissions:
    output: true
    permalink: :name
  docs_dls_fls:
    output: true
    permalink: :name
  docs_audit_logging:
    output: true
    permalink: :name
  docs_rest_api:
    output: true
    permalink: :name
  docs_kibana:
    output: true
    permalink: :name
  docs_elasticstack:
    output: true
    permalink: :name
  docs_other_integrations:
    output: true
    permalink: :name
  docs_systemintegrators:
    output: true
    permalink: :name
  docs_signals:
    output: true
    permalink: :name
  troubleshooting:
    output: true
    permalink: :name
  changelogs:
    output: true
    permalink: :name
  resources:
    output: true
    permalink: :name
  common:
    output: true
    permalink: :name

algolia:
  application_id: '2ESDTH812Y'
  index_name:     '6x-20'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym

eol:
  features:
    - 7.10.2
    - 7.16.2
    - 7.17.x
  updates:
    - n.a.

sgversions:
  # esv |sgv |kbv |available| eol
  search-guard-flx-8:
    - 8.5.3|1.1.0|1.1.0|yes|no
    - 8.5.2|1.1.0|1.1.0|yes|no
    - 8.5.1|1.1.0|1.1.0|yes|no
    - 8.5.0|1.1.0|1.1.0|yes|no

  search-guard-flx-7:
    - 7.17.8|1.1.0|1.1.0|yes|no
    - 7.17.7|1.1.0|1.1.0|yes|no
    - 7.10.2|1.1.0|1.1.0|yes|no    
    - 7.17.6|1.0.0|1.0.0|yes|no
    - 7.17.5|1.0.0|1.0.0|yes|no
    - 7.17.4|1.0.0|1.0.0|yes|no  
    - 7.17.3|1.0.0|1.0.0|yes|no  
    - 7.16.3|1.0.0|1.0.0|yes|no  
  search-guard-suite-7:
    - 7.17.8|53.6.0|53.0.0|yes|no
    - 7.17.7|53.6.0|53.0.0|yes|no
    - 7.17.6|53.5.0|53.0.0|yes|no
    - 7.17.5|53.4.0|53.0.0|yes|no
    - 7.17.4|53.4.0|53.0.0|yes|no
    - 7.17.3|53.4.0|53.0.0|yes|no
    - 7.17.2|53.4.0|53.0.0|yes|no
    - 7.17.1|53.4.0|53.0.0|yes|no
    - 7.17.0|53.4.0|53.0.0|yes|no
    - 7.10.2|53.6.0|53.0.0|yes|no
    - 7.16.3|53.4.0|53.0.0|yes|no
    - 7.16.2|53.4.0|52.2.0|yes|no
    - 7.16.1|52.5.0|52.2.0|yes|no
    - 7.15.2|52.5.0|52.1.0|yes|yes
    - 7.15.1|52.5.0|52.1.0|yes|yes
    - 7.15.0|52.5.0|52.1.0|yes|yes
    - 7.14.2|52.3.0|51.0.0|yes|yes
    - 7.14.1|52.3.0|51.0.0|yes|yes
    - 7.14.0|52.3.0|51.0.0|yes|yes
    - 7.13.4|52.1.0|51.0.0|yes_no_sgadmin|yes
    - 7.13.3|52.1.0|51.0.0|yes_no_sgadmin|yes
    - 7.13.2|52.1.0|51.0.0|yes_no_sgadmin|yes
    - 7.13.1|52.1.0|51.0.0|yes_no_sgadmin|yes
    - 7.13.0|52.1.0|51.0.0|yes_no_sgadmin|yes
    - 7.12.1|51.2.0|51.0.0|yes_no_sgadmin|yes
    - 7.12.0|51.2.0|51.0.0|yes_no_sgadmin|yes
    - 7.11.2|50.3.0|50.1.0|yes_no_sgadmin|yes
    - 7.11.1|50.3.0|50.1.0|yes_no_sgadmin|yes
    - 7.10.1|49.3.0|49.1.0|yes|yes
    - 7.10.0|49.3.0|49.1.0|yes|yes
    - 7.9.3|47.3.0|46.2.0|yes|yes
    - 7.9.2|47.3.0|46.2.0|yes|yes
    - 7.9.1|47.3.0|45.0.0|yes|yes
    - 7.9.0|47.3.0|45.0.0|yes|yes
    - 7.8.1|43.2.0|43.0.0|yes|yes
    - 7.8.0|43.2.0|43.0.0|yes|yes
    - 7.7.1|42.3.0|42.0.0|yes|yes
    - 7.7.0|42.3.0|42.0.0|yes|yes
    - 7.6.2|41.2.0|41.1.0|yes|yes
    - 7.6.1|41.2.0|41.1.0|yes|yes
    - 7.6.0|41.2.0|41.1.0|yes|yes
    - 7.5.2|41.0.0|41.1.0|yes|yes
    - 7.5.1|41.0.0|41.1.0|yes|yes
    - 7.5.0|41.0.0|41.1.0|yes|yes
    - 7.4.2|41.0.0|41.1.0|yes|yes
    - 7.4.1|41.0.0|41.0.0|yes|yes
    - 7.4.0|41.0.0|41.1.0|yes|yes
  search-guard-7:
    - 7.3.2|37.0.0|37.0.0|yes|yes
    - 7.3.1|37.0.0|37.0.0|yes|yes
    - 7.3.0|37.0.0|37.0.0|yes|yes
    - 7.2.1|37.0.0|37.0.0|yes|yes
    - 7.2.0|37.0.0|37.0.0|yes|yes
    - 7.1.1|37.0.0|37.0.0|yes|yes
    - 7.1.0|37.0.0|37.0.0|yes|yes
    - 7.0.1|37.0.0|37.0.0|yes|yes
  search-guard-6:
      #esv |sgv |kbv | available | eol
    - 6.8.23|25.6|19.2|yes|no
    - 6.8.22|25.6|19.2|yes|no
    - 6.8.21|25.6|19.2|yes|no
    - 6.8.17|25.6|19.2|yes|no
    - 6.8.13|25.6|19.2|yes|yes
    - 6.8.12|25.6|19.2|yes|yes
    - 6.8.11|25.6|19.2|yes|yes
    - 6.8.10|25.6|19.2|yes|yes
    - 6.8.9|25.6|19.1|yes|yes
    - 6.8.8|25.6|19.1|yes|yes
    - 6.8.6|25.5|19.0|yes|yes
    - 6.8.5|25.5|19.0|yes|yes
    - 6.8.4|25.5|19.0|yes|yes
    - 6.8.3|25.5|19.0|yes|yes
    - 6.8.2|25.5|19.0|yes|yes
    - 6.8.1|25.5|19.0|yes|yes
    - 6.8.0|25.5|19.0|yes|yes
    - 6.7.2|25.5|19.0|yes|yes
    - 6.7.1|25.5|19.0|yes|yes
    - 6.7.0|25.5|19.0|yes|yes
    - 6.6.2|25.5|19.0|yes|yes
    - 6.6.1|25.5|19.0|yes|yes
    - 6.6.0|25.5|19.0|yes|yes
    - 6.5.4|25.5|19.0|yes|yes
    - 6.5.3|25.5|19.0|yes|yes
    - 6.5.2|25.5|19.0|yes|yes
    - 6.5.1|25.5|19.0|yes|yes
    - 6.4.3|25.5|19.0|yes|yes
    - 6.4.2|25.5|19.0|yes|yes
    - 6.4.1|25.5|19.0|yes|yes
    - 6.4.0|25.5|19.0|yes|yes
  tlstool: 1.9.0
  sgctl: 1.1.0