markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll  

versions:
  - 7.x-35
  - 6.x-25
  - 6.x-24
  - 6.x-23
  - 6.x-22
  - 6.x-21
  - 6.x-20
  - v5
  - v2

currentversion: 5.6.x-19.3

docroots: 
  7.x-35: latest
  6.x-25: 6.x-25
  6.x-24: 6.x-24
  6.x-23: 6.x-23
  6.x-22: 6.x-22
  6.x-21: 6.x-21
  6.x-20: 6.x-20
  v5: v5
  v2: v2

version: v5
islatest: false

index: false

labels:
  navigation:
    quickstart: Quickstart
    installation: Installation
    tls: TLS Setup
    configuration: "Configuration"
    authauth: Authentication and Authorization
    rolespermissions: "Users, Roles and Permissions"
    eeadvanced: Advanced Security Features
    dlsfls: Document- and Field-Level Security
    auditlog: Audit Logging
    restapi: REST API
    esstack: Integrating with the Elastic stack
    xpack: Integrating with X-Pack
    integration_other: Other Integrations
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    7.x-35: Search Guard 7.x-35
    6.x-25: Search Guard 6.x-25
    6.x-24: Search Guard 6.x-24
    6.x-23: Search Guard 6.x-23
    6.x-22: Search Guard 6.x-22
    6.x-21: Search Guard 6.x-21
    6.x-20: Search Guard 6.x-20
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs

relative_links:
  enabled:     true
  collections: true

baseurl: /v5

collections:
  docs:
    output: true
    permalink: :name
  troubleshooting:
    output: true
    permalink: :name
  changelogs:
    output: true
    permalink: :name

algolia:
  application_id: '2ESDTH812Y'
  index_name:     'v5'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym    

sgversions:
  search-guard-5:
    - 5.6.16|5.6.16-19.4|5.6.16-7|no, reached EOL 2019-03-11|link
    - 5.6.15|5.6.15-19.3|5.6.15-7|no, reached EOL 2019-03-11|nolink
    - 5.6.14|5.6.14-19.2|5.6.14-7|no, reached EOL 2019-03-11|nolink
    - 5.6.13|5.6.13-19.2|5.6.13-7|no, reached EOL 2019-03-11|nolink
    - 5.6.10|5.6.10-19.2|5.6.10-7|no, reached EOL 2019-03-11|nolink
    - 5.6.9|5.6.9-19.1|5.6.9-7|no, reached EOL 2019-03-11|nolink
    - 5.6.8|5.6.8-19.1|5.6.8-7|no, reached EOL 2019-03-11|nolink
    - 5.6.7|5.6.7-19.1|5.6.7-6|no, reached EOL 2019-03-11|nolink
    - 5.6.6|5.6.6-19.1|5.6.6-5|no, reached EOL 2019-03-11|nolink
    - 5.6.5|5.6.5-19.1|5.6.5-5|no, reached EOL 2019-03-11|nolink
    - 5.6.4|5.6.4-19.1|5.6.4-5|no, reached EOL 2019-03-11|nolink
    - 5.6.3|5.6.3-19.1|5.6.3-5|no, reached EOL 2019-03-11|nolink
    - 5.6.2|5.6.2-19.1|5.6.2-5|no, reached EOL 2019-03-11|nolink
    - 5.6.0|5.6.0-19.1|5.6.0-4|no, reached EOL 2019-03-11|nolink
    - 5.5.3|5.5.3-16|5.5.3-4|no, reached EOL 2019-01-06|nolink
    - 5.5.2|5.5.2-16|5.5.2-4|no, reached EOL 2019-01-06|nolink
    - 5.5.1|5.5.1-16|5.5.1-4|no, reached EOL 2019-01-06|nolink
    - 5.5.0|5.5.0-16|5.5.0-4|no, reached EOL 2019-01-06|nolink
    - 5.4.3|5.4.3-16|5.4.3-4|no, reached EOL 2018-11-04|nolink
    - 5.4.2|5.4.2-15|5.4.2-4|no, reached EOL 2018-11-04|nolink
    - 5.4.1|5.4.1-15|5.4.1-4|no, reached EOL 2018-11-04|nolink
    - 5.4.0|5.4.0-15|5.4.0-4|no, reached EOL 2018-11-04|nolink
    - 5.3.3|5.3.3-15|5.3.3-4|no, reached EOL 2018-09-28|nolink
    - 5.3.2|5.3.2-15|5.3.2-4|no, reached EOL 2018-09-28|nolink
    - 5.3.1|5.3.1-15|5.3.1-4|no, reached EOL 2018-09-28|nolink
    - 5.3.0|5.3.0-15|5.3.0-4|no, reached EOL 2018-09-28|nolink
    - 5.2.2|5.2.2-15|5.2.2-4|no, reached EOL 2018-07-31|nolink 
    - 5.2.1|5.2.1-15|5.2.1-4|no, reached EOL 2018-07-31|nolink 
    - 5.2.0|5.2.0-15|5.2.0-4|no, reached EOL 2018-07-31|nolink 
    - 5.1.2|5.1.2-15|5.1.2-2|no, reached EOL 2018-06-08|nolink
    - 5.1.1|5.1.1-15|5.1.1-2|no, reached EOL 2018-06-08|nolink
    - 5.0.2|5.0.2-15|5.0.2-2|no, reached EOL 2018-04-26|nolink 
    - 5.0.1|5.0.1-12|-|no, reached EOL 2018-04-26|nolink 
    - 5.0.0|5.0.0-12|-|no, reached EOL 2018-04-26|nolink 
  v2:
    - 2.4.6|2.4.6.14|no, 2.4.x reached EOL 2018-02-28
    - 2.4.5|2.4.5.14|no, 2.4.x reached EOL 2018-02-28
    - 2.4.4|2.4.4.12|no, 2.4.x reached EOL 2018-02-28
    - 2.4.3|2.4.3.12|no, 2.4.x reached EOL 2018-02-28
    - 2.4.2|2.4.2.12|no, 2.4.x reached EOL 2018-02-28
    - 2.4.1|2.4.1.12|no, 2.4.x reached EOL 2018-02-28
    - 2.4.0|2.4.0.12|no, 2.4.x reached EOL 2018-02-28
    - 2.3.5|2.3.5.12|no, 2.3.x reached EOL 2017-09-30
    - 2.3.4|2.3.4.12|no, 2.3.x reached EOL 2017-09-30
    - 2.3.3|2.3.3.12|no, 2.3.x reached EOL 2017-09-30
