markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: "1..2"
  parse_block_html: false
  syntax_highlighter_opts:
    disable: true

sass:
  style: compressed
  sass_dir: ./sass

exclude: ['*.sh', 'build_releasenotes.rb', 'sass', '.idea', '.jekyll-cache']

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll

elasticsearch:
  currentversion: 7.6.0
  previousversion: 7.5.2

searchguard:
  esmajorversion: 7
  version: 7.x-40.0.0 
  fullversion: 7.5.1-40.0.0 
  nextminorversion: 7.5.1-40.1.0 
  nextmajorversion: 7.5.1-41.0.0 
  islatestversion: true
  ispreliminaryversion: false
  allversions:
    - 7x-48
    - 7x-47
    - 7x-46
    - 7x-45
    - 7x-43
    - 7x-42
    - 7x-41
    - 7x-40
    - 7x-38
    - 7x-37
    - 7x-36
    - 7x-35
    - 6x-25
    - 6x-24
    - 6x-23
    - 6x-22
    - 6x-21
    - 6x-20
    - v5
    - v2

docroots: 
  7x-48: latest
  7x-47: 7.x-47  
  7x-46: 7.x-46
  7x-45: 7.x-45
  7x-43: 7.x-43
  7x-42: 7.x-42
  7x-41: 7.x-41
  7x-40: 7.x-40
  7x-38: 7.x-38
  7x-37: 7.x-37
  7x-36: 7.x-36
  7x-35: 7.x-35
  6x-25: 6.x-25
  6x-24: 6.x-24
  6x-23: 6.x-23
  6x-22: 6.x-22
  6x-21: 6.x-21
  6x-20: 6.x-20
  v5: v5
  v2: v2

index: false

labels:
  navigation:
    quickstart: Quickstart
    first_steps: First steps
    versions: Search Guard Versions
    installation: Installing Search Guard
    upgrading: Upgrading Search Guard
    tls: TLS Setup
    ldap: Active Directory / LDAP
    generating-certificates: "Generating certificates"
    configuration: "Search Guard Configuration"
    authauth: Authentication and Authorization
    rolespermissions: "Users, Roles and Permissions"
    eeadvanced: Advanced Security Features
    dlsfls: Document- and Field-Level Security
    kibana: Kibana
    auditlog: Audit And Compliance Logging
    compliance: Compliance
    restapi: REST API
    elasticstack: Integrating with the Elasticstack
    elasticstack-alternatives: "Elasticstack alternatives"
    kibana-authentication: "Kibana Authentication"
    otherintegrations: Other integrations
    systemintegrators: Advanced system integrator features
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    changelogs-kibana: "Kibana Changelogs"
    changelogs-searchguard: "Search Guard Changelogs"
    changelogs-tlstool: "TLS Tool Changelogs"
    resources: Resources
    signals: Signals Alerting
    actions: Alerting Actions
    conditions: Conditions
    inputs: Alerting inputs
    signals-rest: REST API
    security: Alerting Security
    transformations: Transformations
    triggers: Triggers
    sgadmin: sgadmin
    7x-48: Search Guard 7.x-48    
    7x-47: Search Guard 7.x-47
    7x-46: Search Guard 7.x-46    
    7x-45: Search Guard 7.x-45    
    7x-43: Search Guard 7.x-43
    7x-42: Search Guard 7.x-42
    7x-41: Search Guard 7.x-41
    7x-40: Search Guard 7.x-40
    7x-38: Search Guard 7.x-38
    7x-37: Search Guard 7.x-37
    7x-36: Search Guard 7.x-36
    7x-35: Search Guard 7.x-35
    6x-25: Search Guard 6.x-25
    6x-24: Search Guard 6.x-24
    6x-23: Search Guard 6.x-23
    6x-22: Search Guard 6.x-22
    6x-21: Search Guard 6.x-21
    6x-20: Search Guard 6.x-20
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs_quickstart: Documentation
    docs_first_steps: First steps
    docs_versions: Documentation
    docs_installation: Documentation
    docs_tls: Documentation
    docs_configuration_changes: Documentation
    docs_auth_auth: Documentation
    docs_roles_permissions: Documentation
    docs_dls_fls: Documentation
    docs_audit_logging: Documentation
    docs_rest_api: Documentation
    docs_kibana: Documentation
    docs_elasticstack: Documentation
    docs_other_integrations: Documentation
    docs_systemintegrators: Documentation
    docs_signals: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    resources: Resources

relative_links:
  enabled:     true
  collections: true

domain: https://docs.search-guard.com
baseurl: /latest

collections_dir: _content

collections:
  docs_quickstart:
    output: true
    permalink: :title
  docs_first_steps:
    output: true
    permalink: :title
  docs_versions:
    output: true
    permalink: :title
  docs_installation:
    output: true
    permalink: :title
  docs_tls:
    output: true
    permalink: :title
  docs_configuration_changes:
    output: true
    permalink: :title
  docs_auth_auth:
    output: true
    permalink: :title
  docs_roles_permissions:
    output: true
    permalink: :title
  docs_dls_fls:
    output: true
    permalink: :title
  docs_audit_logging:
    output: true
    permalink: :title
  docs_rest_api:
    output: true
    permalink: :title
  docs_kibana:
    output: true
    permalink: :title
  docs_elasticstack:
    output: true
    permalink: :title
  docs_other_integrations:
    output: true
    permalink: :title
  docs_systemintegrators:
    output: true
    permalink: :title
  docs_signals:
    output: true
    permalink: :title
  troubleshooting:
    output: true
    permalink: :title
  changelogs:
    output: true
    permalink: :title
  resources:
    output: true
    permalink: :title
  common:
    output: true
    permalink: :title

algolia:
  application_id: '2ESDTH812Y'
  index_name:     '6x-20'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym

eol:
  features:
    - 7.10.0
  updates:
    - 6.8.10

sgversions:
  # esv |sgv |kbv |available|kbn-artifact-id
  search-guard-suite-7:
    - 7.10.2|48.0.0|48.0.0|yes    
    - 7.10.1|48.0.0|48.0.0|yes  
    - 7.10.0|48.0.0|48.0.0|yes  
    - 7.9.3|47.0.0|46.2.0|yes
    - 7.9.2|46.2.0|46.2.0|yes
    - 7.9.1|45.1.0|45.0.0|yes
    - 7.9.0|45.0.0|45.0.0|yes
    - 7.8.1|43.0.0|43.0.0|yes
    - 7.8.0|43.0.0|43.0.0|yes
    - 7.7.1|42.1.0|42.0.0|yes
    - 7.7.0|42.1.0|42.0.0|yes
    - 7.6.2|41.0.0|41.1.0|yes
    - 7.6.1|41.0.0|41.1.0|yes
    - 7.6.0|41.0.0|41.1.0|yes
    - 7.5.2|41.0.0|41.1.0|yes
    - 7.5.1|41.0.0|41.1.0|yes
    - 7.5.0|41.0.0|41.1.0|yes
    - 7.4.2|41.0.0|41.1.0|yes
    - 7.4.1|41.0.0|41.1.0|yes
    - 7.4.0|41.0.0|41.1.0|yes
  search-guard-7:
    - 7.3.2|37.0.0|37.0.0|yes
    - 7.3.1|37.0.0|37.0.0|yes
    - 7.3.0|37.0.0|37.0.0|yes
    - 7.2.1|37.0.0|37.0.0|yes
    - 7.2.0|37.0.0|37.0.0|yes
    - 7.1.1|37.0.0|37.0.0|yes
    - 7.1.0|37.0.0|37.0.0|yes
    - 7.0.1|37.0.0|37.0.0|yes
  search-guard-6:
      #esv |sgv |kbv |available|kbn-artifact-id
    - 6.8.13|25.6|19.2|yes      
    - 6.8.12|25.6|19.2|yes
    - 6.8.11|25.6|19.2|yes
    - 6.8.10|25.6|19.2|yes
    - 6.8.9|25.6|19.1|yes
    - 6.8.8|25.6|19.1|yes
    - 6.8.6|25.5|19.0|yes
    - 6.8.5|25.5|19.0|yes
    - 6.8.4|25.5|19.0|yes
    - 6.8.3|25.5|19.0|yes
    - 6.8.2|25.5|19.0|yes
    - 6.8.1|25.5|19.0|yes
    - 6.8.0|25.5|19.0|yes
    - 6.7.2|25.5|19.0|no
    - 6.7.1|25.5|19.0|no
    - 6.7.0|25.5|19.0|no
    - 6.6.2|25.5|19.0|no
    - 6.6.1|25.5|19.0|no
    - 6.6.0|25.5|19.0|no
    - 6.5.4|25.5|19.0|no
    - 6.5.3|25.5|19.0|no
    - 6.5.2|25.5|19.0|no
    - 6.5.1|25.5|19.0|no
    - 6.4.3|25.5|19.0|no
    - 6.4.2|25.5|19.0|no
    - 6.4.1|25.5|19.0|no
    - 6.4.0|25.5|19.0|no
    - 6.3.2|25.5|17|no
    - 6.3.1|25.5|17|no
    - 6.3.0|25.5|17|no
    - 6.2.4|23.0|14|no
    - 6.2.3|23.0|14|no
    - 6.2.2|23.0|14|no
    - 6.2.1|23.0|14|no
    - 6.1.4|22.3|12|no
    - 6.1.3|22.3|12|no
    - 6.1.2|22.3|12|no
    - 6.1.1|22.3|12|no
    - 6.1.0|22.3|12|no
  tlstool: 1.8
