markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: "1..2"
  parse_block_html: false
  syntax_highlighter_opts:
    disable: true

sass:
  style: compressed
  sass_dir: ./sass

exclude: ['*.sh', 'build_releasenotes.rb', 'sass', '.idea', '.jekyll-cache', 'README*']

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll

elasticsearch:
  currentversion: 7.6.0
  previousversion: 7.5.2

searchguard:
  esmajorversion: 7
  version: 7.x-40.0.0 
  fullversion: 7.5.1-40.0.0 
  nextminorversion: 7.5.1-40.1.0 
  nextmajorversion: 7.5.1-41.0.0 
  islatestversion: true
  ispreliminaryversion: false
  allversions:
    - 7x-52  
    - 7x-51  
    - 7x-50  
    - 7x-49  
    - 7x-48  
    - 7x-47
    - 7x-46
    - 7x-45
    - 7x-43
    - 7x-42
    - 7x-41
    - 7x-40
    - 7x-38
    - 7x-37
    - 7x-36
    - 7x-35
    - 6x-25
    - 6x-24
    - 6x-23
    - 6x-22
    - 6x-21
    - 6x-20
    - v5
    - v2

docroots: 
  7x-52: latest
  7x-51: 7.x-51
  7x-50: 7.x-50
  7x-49: 7.x-49
  7x-48: 7.x-48
  7x-47: 7.x-47  
  7x-46: 7.x-46
  7x-45: 7.x-45
  7x-43: 7.x-43
  7x-42: 7.x-42
  7x-41: 7.x-41
  7x-40: 7.x-40
  7x-38: 7.x-38
  7x-37: 7.x-37
  7x-36: 7.x-36
  7x-35: 7.x-35
  6x-25: 6.x-25
  6x-24: 6.x-24
  6x-23: 6.x-23
  6x-22: 6.x-22
  6x-21: 6.x-21
  6x-20: 6.x-20
  v5: v5
  v2: v2

index: false

labels:
  navigation:
    introduction: Introduction to Search Guard
    quickstart: Quickstart
    first_steps: First steps
    versions: Search Guard Versions
    installation: Installing Search Guard
    upgrading: Upgrading Search Guard
    tls: TLS Setup
    ldap: Active Directory / LDAP
    generating-certificates: "Generating certificates"
    configuration: "Search Guard Configuration"
    sgctl: "Search Guard CTL"
    authauth: Authentication
    rolespermissions: "Authorization"
    eeadvanced: Advanced Security Features
    dlsfls: Document- and Field-Level Security
    kibana: Kibana
    auditlog: Audit And Compliance Logging
    compliance: Compliance
    restapi: REST API
    elasticstack: Integrating with the Elasticstack
    elasticstack-alternatives: "Elasticstack alternatives"
    kibana-authentication: "Kibana Authentication"
    kibana-authentication-migration-overview: "Migration from v52"
    kibana-advanced: "Kibana Advanced Settings"
    kibana-authentication-basic-overview: "Password based authentication"
    kibana-authentication-openid-overview: "OpenID authentication"
    kibana-authentication-saml-overview: "SAML authentication"
    otherintegrations: Other integrations
    systemintegrators: Advanced system integrator features
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    changelogs-kibana: "Kibana Changelogs"
    changelogs-searchguard: "Search Guard Changelogs"
    changelogs-tlstool: "TLS Tool Changelogs"
    resources: Resources
    signals: Signals Alerting
    actions: Alerting Actions
    conditions: Conditions
    inputs: Alerting inputs
    signals-rest: REST API
    security: Alerting Security
    transformations: Transformations
    triggers: Triggers
    sgadmin: sgadmin
    7x-52: Search Guard 7.x-52     
    7x-51: Search Guard 7.x-51    
    7x-50: Search Guard 7.x-50    
    7x-49: Search Guard 7.x-49    
    7x-48: Search Guard 7.x-48    
    7x-47: Search Guard 7.x-47
    7x-46: Search Guard 7.x-46    
    7x-45: Search Guard 7.x-45    
    7x-43: Search Guard 7.x-43
    7x-42: Search Guard 7.x-42
    7x-41: Search Guard 7.x-41
    7x-40: Search Guard 7.x-40
    7x-38: Search Guard 7.x-38
    7x-37: Search Guard 7.x-37
    7x-36: Search Guard 7.x-36
    7x-35: Search Guard 7.x-35
    6x-25: Search Guard 6.x-25
    6x-24: Search Guard 6.x-24
    6x-23: Search Guard 6.x-23
    6x-22: Search Guard 6.x-22
    6x-21: Search Guard 6.x-21
    6x-20: Search Guard 6.x-20
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs_introduction: Introduction to Search Guard
    docs_quickstart: Documentation
    docs_first_steps: First steps
    docs_versions: Documentation
    docs_installation: Documentation
    docs_tls: Documentation
    docs_configuration_changes: Documentation
    docs_auth_auth: Documentation
    docs_roles_permissions: Documentation
    docs_dls_fls: Documentation
    docs_audit_logging: Documentation
    docs_rest_api: Documentation
    docs_kibana: Documentation
    docs_elasticstack: Documentation
    docs_other_integrations: Documentation
    docs_systemintegrators: Documentation
    docs_signals: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    resources: Resources

relative_links:
  enabled:     true
  collections: true

#domain: https://docs.search-guard.com
#baseurl: /tech-preview

collections_dir: _content

collections:
  docs_introduction:
    output: true
    permalink: :name
  docs_quickstart:
    output: true
    permalink: :name
  docs_versions:
    output: true
    permalink: :name
  docs_installation:
    output: true
    permalink: :name
  docs_tls:
    output: true
    permalink: :name
  docs_configuration_changes:
    output: true
    permalink: :name
  docs_auth_auth:
    output: true
    permalink: :name
  docs_roles_permissions:
    output: true
    permalink: :name
  docs_dls_fls:
    output: true
    permalink: :name
  docs_audit_logging:
    output: true
    permalink: :name
  docs_rest_api:
    output: true
    permalink: :name
  docs_kibana:
    output: true
    permalink: :name
  docs_elasticstack:
    output: true
    permalink: :name
  docs_other_integrations:
    output: true
    permalink: :name
  docs_systemintegrators:
    output: true
    permalink: :name
  docs_signals:
    output: true
    permalink: :name
  troubleshooting:
    output: true
    permalink: :name
  changelogs:
    output: true
    permalink: :name
  resources:
    output: true
    permalink: :name
  common:
    output: true
    permalink: :name

algolia:
  application_id: '2ESDTH812Y'
  index_name:     '6x-20'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym

eol:
  features:
    - 7.11.0
  updates:
    - 6.8.10

sgversions:
  # esv |sgv |kbv |available| eol
  search-guard-flx-7:
    - 7.17.3|1.0.0-beta-2|1.0.0-beta-2|yes|no  
    - 7.16.3|1.0.0-beta-2|1.0.0-beta-2|yes|no  
    - 7.10.2|1.0.0-beta-2|1.0.0-beta-2|yes|no    
  tlstool: 1.8
  sgctl: 1.0.0-beta-2